# Site settings
title: Jeroen Reijn
subtitle: About Java and software development
author: Jeroen Reijn
email:
description: "I work at Hippo. I'm a dad, programmer, consultant and occasional speaker."
baseurl: ""
url: "http://blog.jeroenreijn.com"

# Build settings
markdown: redcarpet
permalink: :year/:month/:title.html

paginate: 5

username: jreijn
disqus_short_name: blogjeroenreijn

gems:
  - jekyll-mentions
  - jekyll-sitemap
