# Site settings
title: Community Analytics
subtitle: "That's what we do"
author: Bas van Leeuwen
email:
description: "Actionable insights on community analytics"
#copyright: "© - "
baseurl: ""
url: "http://blog.community-analytics.com"
#atom_path: "atom.xml"

# Build settings
markdown: redcarpet
permalink: :year/:month/:title.html

paginate: 5

#username: jreijn
#disqus_short_name: blogjeroenreijn

sitemap:
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feeds/posts/default"

gems:
  - jekyll-sitemap
